### PR TITLE
Added new parameter to handle "plus trick" in mail

### PR DESCRIPTION
**Pull request by marbink**
Added also a new example in README to show how to use it.

### CODE REVIEW

**Comment by SysQo** [comment]
Not working.

you are using list function incorrectly.

here is my traceback: 

`Traceback (most recent call last):
  File "C:\Python27\Scripts\pikapy-script.py", line 9, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "c:\python27\lib\site-packages\pikapy\console.py", line 60, in entry
    account_info = pikapy.random_account(args.username, args.password, args.email, args.birthday, args.plusmail)
  File "c:\python27\lib\site-packages\pikapy\accountcreator.py", line 199, in random_account
    try_email = pm[0] + "+" + try_username + "@" + pm[1]
IndexError: list index out of range`

**Comment by marbink** [comment]
I used it to create some account before upload. It should work correctly.
Did you write email like this "mail+@example.com"? (I mean with + char)

Il mercoledì 17 agosto 2016, Jesse Frederick <notifications@github.com> ha
scritto:

**Comment by SysQo** [comment]
Ah, i must have misread your readme. sorry about this. Works perfect

+1 on pull - epic feature

**Comment by skvvv** [comment]
I'll edit the readme, might be confusing for some people as the plus prefix is a random string itself.

Will push as soon as I get home.

+1

**Pull request merged**
